version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: es01-flow-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 9200:9200
    volumes:
      - storefrontdata:/usr/share/elasticsearch/data
    networks:
      - elastic
    labels:
      - co.elastic.logs/module=elasticsearch
      - co.elastic.metrics/module=elasticsearch
networks:
  elastic:
    driver: bridge
volumes:
  storefrontdata:
    driver: local
